### ISSUE TITLE
Hello Contributors! We need help removing the Background of our logo :)

### ISSUE THREAD

**Issue by fabianbernhart** [JadKHaddad-ORG/serial-vau#4]
![rustCrabSerialVau](https://github.com/user-attachments/assets/8593c5bf-96a0-43de-a482-22743bf55471)

**Comment by JadKHaddad** [comment]
Mach mal PNG mit transparentem Hintergrund und pack es mal in `/assets/logo.png`

**Comment by fabianbernhart** [comment]
![file](https://github.com/user-attachments/assets/54d58cd8-191f-47e1-8080-1458abc4d0cf)

Das hat sso ein Weißen Hihntergrund :/

**Comment by JadKHaddad** [comment]
Die Augen auch :/

Gibt es nicht ein fertiges ferris png ohne Hintergrund?

**Comment by fabianbernhart** [comment]
ja das ist ohne Hintergrund doch canva hat den dann so doof entfernt ich schau mal ob ich das mit Adobe Express lösen kann

**Comment by fabianbernhart** [comment]
![Design ohne Titel(1)](https://github.com/user-attachments/assets/8b587ea8-79f2-49ab-9304-051ff449b2ba)

**Comment by JadKHaddad** [comment]
Auf einem schwarzen Hintergrund sieht man die Ränder noch

**Comment by fabianbernhart** [comment]
Mach hier mal Help wanted Tag dran

**Comment by fabianbernhart** [comment]
Pin das auch mal an

**Comment by fabianbernhart** [comment]
![rustCrabSerialVau](https://github.com/user-attachments/assets/dba94bdb-61ec-4978-b5d5-7cb33f0f8fbc)

**Comment by fabianbernhart** [comment]
@JadKHaddad Done
